server:
  port: 9999

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
  flyway:
    locations: classpath:db/migration
    enabled: true

custom:
  aws:
    iot:
      endPoint: "${IOT_ENDPOINT}"
      certificatePath: "${IOT_CERT_PATH:${user.dir}/auth/certificate.pem.crt}"
      privateKeyPath: "${IOT_PRIVATE_KEY_PATH:${user.dir}/auth/private.pem.key}"
  thing:
    name: "${THING_NAME}"
